### ISSUE TITLE
what are eClient and eId?

### ISSUE THREAD

**Issue by cartazio** [uwplse/verdi#18]
hey!

I've been working through your Raft imlementation, and I can figure out *what* the natural numbers for the `eClient` and `eID` fields represent?

```
 Record entry := mkEntry {
                      eAt : name;
                      eClient : nat;
                      eId : nat;
                      eIndex : logIndex;
                      eTerm : term;
                      eInput : input
                    }.

```

some clarity would be much appreciated, me and a colleague have been trying to figure out if those Naturals are actually Names, terms, or what?! 

many thanks
-Carter

**Comment by wilcoxjay** [comment]
Those two fields are for implementing linearizable semantics, as described in Chapter 6 of Diego's thesis: https://ramcloud.stanford.edu/~ongaro/raftproof.pdf . 

Each client is assigned a client name out of band. Clients also assign unique IDs to their requests. These are attached to commands in the raft_input type, and recorded by the raft servers in the eClient and eId fields. (Perhaps a better name for eId would be eSeqNum. We accept pull requests :wink:.) The raft servers keep track of client sessions using the clientCache part of raft_data. If a client sends a duplicate request, the raft cluster responds using the cache instead of reexecuting the command. This provides exactly once linearizable semantics.

Let us know if you have any other questions about our totally undocumented implementation :)

I'd also be curious to hear what you're planning on doing with it!
